#include "main.h"
#include "GDEHDotDisp.h"

int main()
{

  GDESPI SPI = { GPIO_PIN_8, GPIOA, //MISO
		  GPIO_PIN_5,GPIOA, //MOSI
		  GPIO_PIN_7, GPIOA, //SCK
		  GPIO_PIN_4,GPIOA,  //CSS
		  GPIO_PIN_2,GPIOA,  //DC
		  GPIO_PIN_1, GPIOA, //RST
		  GPIO_PIN_3, GPIOA, //BS
		  0X01
  };
  GDEH_GATE_VOLTAGE VOLT=VGH_20;
   GDEH_ENTRY_SEQ SQ=0x00;
   GDEH_WFM_CTL WFM={0x00,0x00,0x01,0x01};
   GDEH_Display_Update UPD={0x00, 0x80, EN_CLK_EN_AN_T_LUTM1_DSB_CLK_DSB_OSC};
   GDEH GDE={3,GDEH_DEFAULT_GATE_SCAN_DIR,128,296,VOLT,SQ,WFM,UPD,SPI};
  GDESPI_INIT(GDE.SPI);
  while(1)
  {

	 GDEH_INIT(GDE);
	 GDEH_WRITE(GDE,gImage_BW,gImage_R,4736, 1);
	 GDEH_GO_SLEEP(GDE,GDEH_SM_1);
	 HAL_Delay(10000);
  }
return 0;
}
