#include "GDEHDotDisp.h"

void GDEH_BUSY_CHECK()
{
while(isEPD_W21_BUSY);
}

void GDEH_INIT(GDEH GDE)
{
	EPD_W21_Init();

	GDEH_RESET;

	EPD_W21_WriteCMD(GDEH_DRIVER_CONTROL_CMD);

	uint8_t temp=GDE.width&0xFF;
	EPD_W21_WriteDATA(temp);

	temp=GDE.width>>8&0xff;
	EPD_W21_WriteDATA(temp);

	if(!GDE.gate_drive)EPD_W21_WriteDATA(GDEH_DEFAULT_GATE_SCAN_DIR);
    else EPD_W21_WriteDATA(GDE.gate_drive);

	if(!GDE.VOLTAGE)GDEH_WRITE_VOLTAGE(GDEH_DEFAULT_VOLTAGE);
	else GDEH_WRITE_VOLTAGE(GDE.VOLTAGE);

	GDEH_WRITE_SOURCE_VOLTAGE(15,-15);

	GDEH_INITIAL_CODE;

	if(!GDE.SEQUENCE)GDEH_ENTRYMODE_SETTINGS(0x03);
	else GDEH_ENTRYMODE_SETTINGS(GDE.SEQUENCE);

	GDEH_SET_POSITION(0,GDE.height,0, GDE.width);

	if(!GDE.WFV.TRANS_CNTL)
	{
		GDEH_WFM_CTL WFM={GDEH_WFM_CTL_DEFAULT, 0x00, 0x00,0x00};
		GDEH_WAVEFORM_CTL(GDE.WFM);
	}
	else GDEH_WAVEFORM_CTL(GDE.WFV);

	if(!GDE.UPD.ColorOpt)
	{
		GDEH_Display_Update UPD;
		UPD.ColorOpt=0x00;
		UPD.SourceMode=0x80;
		UPD.StageMaster=0xFF;

	}
	else GDEH_UPD_CNT(GDE.UPD);

	GDEH_SET_ADDRESS_CNTR(GDE.height, GDE.width);
	GDEH_BUSY_CHECK();
}

void GDEH_WRITE_VOLTAGE(GDEH_GATE_VOLTAGE Voltage)
{
	EPD_W21_WriteCMD(GDEH_DRIVING_VOLTAGE_CMD);
	EPD_W21_WriteDATA(Voltage);
}

void GDEH_WRITE_SOURCE_VOLTAGE(float Voltage, float VSL)
{
  uint8_t V;
  if(Voltage>8.9) V=Voltage*10;
  else V=Voltage*5;
  EPD_W21_WriteCMD(GDEH_DRIVING_VOTLTAGE_SRC_CMD);
  EPD_W21_WriteDATA(V);
  EPD_W21_WriteDATA(0x01);
  EPD_W21_WriteDATA(abs(VSL*2));
}




void GDEH_WRITE_REG_INI_CODE()
{
	EPD_W21_WriteCMD(GDEH_INITIAL_CODE_SETTING_CMD);
	EPD_W21_WriteDATA(0x01);
	EPD_W21_WriteDATA(0x01);
	EPD_W21_WriteDATA(0x01);
}

uint8_t GDEH_READ_REG()
{
	EPD_W21_WriteCMD(GDEH_READ_INITIAL_CODE_SETTINGS_CMD);
	return SPI_Read();
}

void GDEH_BOOST_START(GDEH_SOFT_START SOFT)
{
	EPD_W21_WriteCMD(GDEH_READ_INITIAL_CODE_SETTINGS_CMD);
	EPD_W21_WriteDATA(SOFT.A_phase);
	EPD_W21_WriteDATA(SOFT.B_phase);
	EPD_W21_WriteDATA(SOFT.C_phase);
	EPD_W21_WriteDATA(SOFT.D_duration);
}

void GDEH_GO_SLEEP(GDEH_DEEP_SLEEP Sleep)
{
	EPD_W21_WriteCMD(GDEH_DEEP_SLEEP_MODE_CMD);
	EPD_W21_WriteDATA(Sleep);
}

void GDEH_ENTRYMODE_SETTINGS(GDEH_ENTRY_SEQ SEQ)
{
	EPD_W21_WriteCMD(GDEH_DATA_ENTRY_MODE_SETTING_CMD);
	EPD_W21_WriteDATA(SEQ);
}



void GDEH_VCI_DETECTION(GDEH_VCI_DETECT VCI)
{
	EPD_W21_WriteCMD(GDEH_VCI_DETECTION_CMD);
	EPD_W21_WriteDATA(VCI);
}


void GDEH_TEMP_CNTL(uint16_t SensCNT)
{
	EPD_W21_WriteCMD(GDEH_TEMP_SENSOR_CNTL_CHS_CMD);
	EPD_W21_WriteDATA(SensCNT&0xFF);
	EPD_W21_WriteDATA((SensCNT>>8)&0xFF);
}


uint16_t GDEH_TEMP_READ()
{
	uint16_t temp=0;

	return 	temp;
}



void GDEH_UPD_CNT(GDEH_Display_Update UPD)
{
	EPD_W21_WriteCMD(GDEH_DISPLAY_UPD_CNTL_CMD);
	EPD_W21_WriteDATA(UPD.ColorOpt);
	EPD_W21_WriteDATA(UPD.SourceMode);
	EPD_W21_WriteCMD(GDEH_DISPLAY_UPD_CNTL_2_CMD);
	EPD_W21_WriteDATA(UPD.StageMaster);
}


uint8_t GDEH_READ_RAM()
{
uint8_t readed=0;

return readed;
}

void GDEH_VCOM_SENSE_Duration(uint8_t Duration)
{
	EPD_W21_WriteCMD(GDEH_VCOM_SENS_CMD);
	EPD_W21_WriteCMD(GDEH_VCOM_SENSE_DURATION_CMD);
	EPD_W21_WriteDATA(Duration);
}




uint8_t GDEH_WRITE_VCOM(float VCOM) //return
{
	uint8_t temp= abs(VCOM*10)*4;
	EPD_W21_WriteCMD(GDEH_WR_VCOM_REG_CMD);
	EPD_W21_WriteDATA(temp);
	return temp;
}



void GDEH_WRITE_REGS_FOR_DISP_OPT_USER(uint8_t* DATA, uint8_t user)
{
	if(user) EPD_W21_WriteCMD(GDEH_WR_REG_USER_ID_CMD);
	else EPD_W21_WriteCMD(GDEH_WR_REG_DISP_IOT_CMD);
	for(uint8_t i=0; i<10;i++)
	{
		EPD_W21_WriteDATA(DATA+i);
	}
}

void GDEH_WAVEFORM_CTL(GDEH_WFM_CTL WFM)
{
	EPD_W21_WriteCMD(GDEH_WVF_CNTL_CMD);
	EPD_W21_WriteDATA(WFM.VBD<<6|WFM.VBD_FLS<<4|WFM.TRANS_CNTL<<2|WFM.VBD_LUT);
}


void GDEH_SET_POSITION(uint8_t X_Start, uint8_t X_End, uint16_t Y_Start, uint16_t Y_End)
{
	EPD_W21_WriteCMD(GDEH_SET_X_ADDR_START_END_CMD);
	EPD_W21_WriteDATA(X_Start);
	EPD_W21_WriteDATA(X_End);
	EPD_W21_WriteCMD(GDEH_SET_Y_ADDR_START_END_CMD);
	EPD_W21_WriteDATA(Y_Start);
	EPD_W21_WriteDATA(Y_End);
}

void GDEH_SET_ADDRESS_CNTR(uint8_t ADRX, uint16_t ADRY)
{
	EPD_W21_WriteCMD(GDEH_XSET_CNTR_CMD);
	EPD_W21_WriteDATA(ADRX);

	EPD_W21_WriteCMD(GDEH_YSET_CNTR_CMD);
	EPD_W21_WriteDATA(ADRY&0xFF);
	EPD_W21_WriteDATA((ADRY>>8)&0xFF);
}

