#include "GDEHDotDisp.h"

void GDEH_BUSY_CHECK(GDEH GDE)
{
	while(GDESPI_GPIO_READ(GDE.SPI.BS_PORT,GDE.SPI.BS));
}

void GDEH_INIT(GDEH GDE)
{

	GDESPI_GPIO_RESET(GDE.SPI.RST_PORT, GDE.SPI.RST);
	GDESPI_Delay_MS(1000);
	GDESPI_GPIO_SET(GDE.SPI.RST_PORT, GDE.SPI.RST);
	GDESPI_Delay_MS(1000);

	GDEH_BUSY_CHECK(GDE);
	GDEH_RESET(GDE);

	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DRIVER_CONTROL_CMD);

	uint8_t temp=((GDE.width-1)&0xFF);
	GDESPI_WRITE_DATA(GDE.SPI,temp);

	temp=GDE.width>>8&0xff;
	GDESPI_WRITE_DATA(GDE.SPI,temp);

	if(!GDE.gate_drive)GDESPI_WRITE_DATA(GDE.SPI,GDEH_DEFAULT_GATE_SCAN_DIR);
    else GDESPI_WRITE_DATA(GDE.SPI,GDE.gate_drive);

	/*if(!GDE.VOLTAGE)GDEH_WRITE_VOLTAGE(GDEH_DEFAULT_VOLTAGE);
	else GDEH_WRITE_VOLTAGE(GDE.VOLTAGE);

	GDEH_WRITE_SOURCE_VOLTAGE(15,-15);
	 */
	//GDEH_INITIAL_CODE;

	if(!GDE.SEQUENCE)GDEH_ENTRYMODE_SETTINGS(GDE,0x01);
	else GDEH_ENTRYMODE_SETTINGS(GDE,GDE.SEQUENCE);

	GDEH_SET_POSITION(GDE,0,GDE.height, GDE.width,0);

	if(!GDE.WFV.TRANS_CNTL)
	{
		GDEH_WFM_CTL WFM={0x00, 0x00,0x00,GDEH_WFM_CTL_DEFAULT};
		GDEH_WAVEFORM_CTL(GDE,GDE.WFV);
	}
	else GDEH_WAVEFORM_CTL(GDE,GDE.WFV);

	if(!GDE.UPD.ColorOpt)
	{
		GDEH_Display_Update UPD;
		UPD.ColorOpt=0x00;
		UPD.SourceMode=0x80;
		UPD.StageMaster=0xF7;
		GDEH_UPD_CNT(GDE,UPD);
	}
	else GDEH_UPD_CNT(GDE,GDE.UPD);

	GDEH_SET_ADDRESS_CNTR(GDE,0, GDE.width);

}

void GDEH_WRITE_VOLTAGE(GDEH GDE, GDEH_GATE_VOLTAGE Voltage)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DRIVING_VOLTAGE_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,Voltage);
}

void GDEH_WRITE_SOURCE_VOLTAGE(GDEH GDE,float Voltage, float VSL)
{
  uint8_t V;
  if(Voltage>8.9) V=Voltage*10;
  else V=Voltage*5;
  GDESPI_WRITE_CMD(GDE.SPI,GDEH_DRIVING_VOTLTAGE_SRC_CMD);
  GDESPI_WRITE_DATA(GDE.SPI,V);
  GDESPI_WRITE_DATA(GDE.SPI,0x01);
  GDESPI_WRITE_DATA(GDE.SPI,abs(VSL*2));
}




void GDEH_WRITE_REG_INI_CODE(GDEH GDE)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_INITIAL_CODE_SETTING_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,0x01);
	GDESPI_WRITE_DATA(GDE.SPI,0x01);
	GDESPI_WRITE_DATA(GDE.SPI,0x01);
}

uint8_t GDEH_READ_REG(GDEH GDE)
{
	uint8_t output=0;
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_READ_INITIAL_CODE_SETTINGS_CMD);
	return output;
}

void GDEH_BOOST_START(GDEH GDE, GDEH_SOFT_START SOFT)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_READ_INITIAL_CODE_SETTINGS_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,SOFT.A_phase);
	GDESPI_WRITE_DATA(GDE.SPI,SOFT.B_phase);
	GDESPI_WRITE_DATA(GDE.SPI,SOFT.C_phase);
	GDESPI_WRITE_DATA(GDE.SPI,SOFT.D_duration);
}

void GDEH_GO_SLEEP(GDEH GDE,GDEH_DEEP_SLEEP Sleep)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DEEP_SLEEP_MODE_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,Sleep);

}

void GDEH_ENTRYMODE_SETTINGS(GDEH GDE,GDEH_ENTRY_SEQ SEQ)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DATA_ENTRY_MODE_SETTING_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,SEQ);
}



void GDEH_VCI_DETECTION(GDEH GDE,GDEH_VCI_DETECT VCI)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_VCI_DETECTION_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,VCI);
	GDEH_BUSY_CHECK(GDE);
}


void GDEH_TEMP_CNTL(GDEH GDE,uint16_t SensCNT)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_TEMP_SENSOR_CNTL_CHS_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,SensCNT&0xFF);
	GDESPI_WRITE_DATA(GDE.SPI,(SensCNT>>8)&0xFF);
	GDEH_BUSY_CHECK(GDE);
}


uint16_t GDEH_TEMP_READ()
{
	uint16_t temp=0;

	return 	temp;
}



void GDEH_UPD_CNT(GDEH GDE,GDEH_Display_Update UPD)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DISPLAY_UPD_CNTL_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,UPD.ColorOpt);
	GDESPI_WRITE_DATA(GDE.SPI,UPD.SourceMode);
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_DISPLAY_UPD_CNTL_2_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,UPD.StageMaster);
}


uint8_t GDEH_READ_RAM()
{
uint8_t readed=0;

return readed;
}

void GDEH_VCOM_SENSE_Duration(GDEH GDE,uint8_t Duration)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_VCOM_SENS_CMD);
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_VCOM_SENSE_DURATION_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,Duration);
	GDEH_BUSY_CHECK(GDE);
}




uint8_t GDEH_WRITE_VCOM(GDEH GDE, float VCOM) //return
{
	uint8_t temp= abs(VCOM*10)*4;
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_WR_VCOM_REG_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,temp);
	GDEH_BUSY_CHECK(GDE);
	return temp;
}



void GDEH_WRITE_REGS_FOR_DISP_OPT_USER(GDEH GDE,uint8_t* DATA, uint8_t user)
{
	if(user) GDESPI_WRITE_CMD(GDE.SPI,GDEH_WR_REG_USER_ID_CMD);
	else GDESPI_WRITE_CMD(GDE.SPI,GDEH_WR_REG_DISP_IOT_CMD);
	for(uint8_t i=0; i<10;i++)
	{
		GDESPI_WRITE_DATA(GDE.SPI,DATA+i);
	}

}

void GDEH_WAVEFORM_CTL(GDEH GDE,GDEH_WFM_CTL WFM)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_WVF_CNTL_CMD);
	uint8_t WF=WFM.VBD<<6|WFM.VBD_FLS<<4|WFM.TRANS_CNTL<<2|WFM.VBD_LUT;
	GDESPI_WRITE_DATA(GDE.SPI,WF);
	//GDESPI_WRITE_DATA(GDE.SPI,0x05);
}


void GDEH_SET_POSITION(GDEH GDE,uint8_t X_Start, uint8_t X_End, uint16_t Y_Start, uint16_t Y_End)
{
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_SET_X_ADDR_START_END_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,X_Start);
	uint8_t temp= (X_End/8)-1;
	GDESPI_WRITE_DATA(GDE.SPI,temp);
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_SET_Y_ADDR_START_END_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,Y_Start);
	GDESPI_WRITE_DATA(GDE.SPI,(Y_Start>>8)&0x01);
	GDESPI_WRITE_DATA(GDE.SPI,Y_End);
	GDESPI_WRITE_DATA(GDE.SPI,(Y_End>>8)&0x01);

}

void GDEH_SET_ADDRESS_CNTR(GDEH GDE,uint8_t ADRX, uint16_t ADRY)
{
	ADRY=ADRY-1;
	GDESPI_WRITE_CMD(GDE.SPI,GDEH_XSET_CNTR_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,ADRX);

	GDESPI_WRITE_CMD(GDE.SPI,GDEH_YSET_CNTR_CMD);
	GDESPI_WRITE_DATA(GDE.SPI,ADRY&0xFF);
	GDESPI_WRITE_DATA(GDE.SPI,(ADRY>>8)&0xFF);
	GDEH_BUSY_CHECK(GDE);
}

/*******************USER FUNCTIONS***************/
void GDEH_UPDATE(GDEH GDE)
{
	  GDESPI_WRITE_CMD(GDE.SPI,GDEH_DISPLAY_UPD_CNTL_2_CMD ); //Display Update Control
	  GDESPI_WRITE_DATA(GDE.SPI,EN_CLK_EN_AN_T_LUTM1_DSB_CLK_DSB_OSC);
	  GDESPI_WRITE_CMD(GDE.SPI,GDEH_MASTER_ACTIVATION_CMD);  //Activate Display Update Sequence
	  GDEH_BUSY_CHECK(GDE);
}



void GDEH_WRITE(GDEH GDE,uint8_t *BLACK_WHITE, uint8_t* RED, int SIZE, uint8_t INVERSE)
{
	GDEH_Write_BW(GDE);
	for(int i=0; i<SIZE; i++)
	{
		GDESPI_WRITE_DATA(GDE.SPI,*BLACK_WHITE);
		BLACK_WHITE++;
	}
	GDESPI_Delay_MS(20);
	GDEH_Write_RED(GDE);
	for(int i=0; i<SIZE; i++)
	{
		if(!INVERSE) GDESPI_WRITE_DATA(GDE.SPI,*RED);
		else GDESPI_WRITE_DATA(GDE.SPI,~(*RED));
		RED++;
	}
	GDESPI_Delay_MS(20);
	GDEH_UPDATE(GDE);
}

void GDEH_CLEAR(GDEH GDE,int SIZE)
{
	GDEH_Write_BW(GDE);
	for(int i=0; i<SIZE; i++)
	{
		GDESPI_WRITE_DATA(GDE.SPI,0xFF);
	}
	GDEH_Write_RED(GDE);
	for(int i=0; i<SIZE; i++)
	{
		GDESPI_WRITE_DATA(GDE.SPI,0x00);
	}
	GDEH_UPDATE(GDE);
}

